      - name: Build Electron (macOS)
        if: matrix.platform == 'mac'
        run: npx electron-builder --mac --${{ matrix.arch }} --publish never
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'